export const queryKeys = {
  todoBoard: ['todo-board'] as const,
  completedTodos: ['todos', 'completed'] as const,
  todoContacts: (todoId: string) => ['todo-contacts', todoId] as const,
  todoUpdates: (todoId: string) => ['todo-updates', todoId] as const,
  labels: ['labels'] as const,
  archivedLabels: ['labels', 'archived'] as const,
  people: ['people'] as const,
  notebook: ['notebook'] as const,
  notebookNote: (id: string) => ['notebook', id] as const,
  accomplishments: (year: number) => ['accomplishments', year] as const,
  yearStats: (year: number) => ['stats', 'year', year] as const,
  githubPrStatus: (url: string) => ['github-pr', url] as const,
  githubIssueStatus: (url: string) => ['github-issue', url] as const,
  azureWorkItemStatus: (url: string) => ['azure-workitem', url] as const,
  localAiStatus: ['local-ai', 'status'] as const,
  vpnStatus: ['vpn-status'] as const,
}
